access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  #  data:
  #    mongodb:
  #      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?authSource=${MONGODB_DB}&replicaSet=${MONGODB_RS}
  #      database: ${MONGODB_DB}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8000
